[project]
name = "registry-cache"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "kubernetes>=34.1.0",
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-gcp>=9.0.0,<10.0.0",
    "pulumi-kubernetes>=4.0.0,<5.0.0",
]
